spring:
  application:
    name: item-service
  profiles:
    active: dev
info:
  version: ‘@project.version@’
endpoints:
  shutdown:
    enabled: true
server:
  port: 0
mongeez:
  location: mongo-changelog/changelog-master.xml

eureka:

client:
 serviceUrl:
 defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
instance:
 preferIpAddress: true
---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      database: item-service

---
spring:
  profiles: docker
  data:
    mongodb:
      host: itemservicedb
      database: itemservice
